"""empty message

Revision ID: 4f6b52a4a531
Revises: 7a3a1667c5f5
Create Date: 2021-03-19 12:39:58.467709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6b52a4a531'
down_revision = '7a3a1667c5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('age', sa.String(length=120), nullable=True))
    op.add_column('signup', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup', 'name')
    op.drop_column('signup', 'age')
    # ### end Alembic commands ###
