"""empty message

Revision ID: 8877e4e7dbde
Revises: 4f6b52a4a531
Create Date: 2021-03-19 12:47:32.952637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8877e4e7dbde'
down_revision = '4f6b52a4a531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('email_address', sa.String(length=255), nullable=True))
    op.drop_column('signup', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('signup', 'email_address')
    # ### end Alembic commands ###
