"""empty message

Revision ID: b9e71c217e19
Revises: 8877e4e7dbde
Create Date: 2021-03-19 12:51:56.908055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9e71c217e19'
down_revision = '8877e4e7dbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('signup', 'email_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('signup', 'email')
    # ### end Alembic commands ###
